export {ReactComponent as ArrowRight} from './arrow_right.svg';
export {ReactComponent as Car} from './car.svg';
export {ReactComponent as Dictionary} from './dictionary.svg';
export {ReactComponent as L} from './l.svg';
export {ReactComponent as More1} from './more1.svg';
export {ReactComponent as More2} from './more2.svg';
export {ReactComponent as ProgressBar} from './progressBar.svg';
export {ReactComponent as ProgressSelected} from './progress_selected.svg';
export {ReactComponent as Selector} from './selector.svg';
